"""add_language_and_updated_at_columns

Revision ID: 6ee1ace48205
Revises: e0eb441eeaa0
Create Date: 2026-09-27 08:05:25.043987

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ee1ace48205'
down_revision: str | Sequence[str] | None = 'e0eb441eeaa0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('language', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE documents SET updated_at = created_at')
    op.alter_column('documents', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'language')
    # ### end Alembic commands ###
